[profile.release]
panic = "unwind"
opt-level = 3

[profile.production]
inherits = "release"
lto = true
codegen-units = 1

[workspace]
resolver = "2"

members = [
    "primitives",
    "node",
    "runtime",
    "pallets/*",
]

exclude = [
    "contracts",
]
