module.exports = class Data1681979340403 {
    name = 'Data1681979340403'

    async up(db) {
        await db.query(`CREATE TABLE "impl_build" ("id" character varying NOT NULL, "impl_id" integer NOT NULL, "version" integer NOT NULL, "status" character varying(12) NOT NULL, "magic_bytes" text, "online_workers_count" integer NOT NULL, "tasks_count" integer NOT NULL, "successful_tasks_count" integer NOT NULL, "failed_tasks_count" integer NOT NULL, "errored_tasks_count" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "deleted_at" TIMESTAMP WITH TIME ZONE, "_impl_id" character varying, CONSTRAINT "PK_5a7367725014a952d56efb311d2" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_fc6f6b9ac54614cd699fc5dd74" ON "impl_build" ("_impl_id") `)
        await db.query(`CREATE TABLE "pool_workers" ("id" character varying NOT NULL, "pool_id" integer NOT NULL, "worker_address" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "deleted_at" TIMESTAMP WITH TIME ZONE, "_pool_id" character varying, "_worker_id" character varying, CONSTRAINT "PK_1e1e55d91deabf4a8d10e73b7e0" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_a1959943ab30eb084ebdee7525" ON "pool_workers" ("_pool_id") `)
        await db.query(`CREATE INDEX "IDX_d5e39bcd7ed93dbc3cf61aaf70" ON "pool_workers" ("_worker_id") `)
        await db.query(`CREATE TABLE "creating_task_policy" ("id" character varying NOT NULL, "policy_id" integer NOT NULL, "permission" character varying(6) NOT NULL, "start_block" integer, "end_block" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "deleted_at" TIMESTAMP WITH TIME ZONE, "_pool_id" character varying, CONSTRAINT "PK_f7ec0f93d732904de02842b723c" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_0a1b9b9a2968014eba32b94bbb" ON "creating_task_policy" ("_pool_id") `)
        await db.query(`CREATE TABLE "task_event" ("id" character varying NOT NULL, "kind" character varying(10) NOT NULL, "payload" text, "block_number" integer NOT NULL, "block_time" TIMESTAMP WITH TIME ZONE NOT NULL, "_task_id" character varying, CONSTRAINT "PK_5512953f207de074aea7e6b1515" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_95b5d139a6cc677f8a719f3eb4" ON "task_event" ("_task_id") `)
        await db.query(`CREATE TABLE "task" ("id" character varying NOT NULL, "task_id" integer NOT NULL, "pool_id" integer NOT NULL, "policy_id" integer NOT NULL, "owner_address" text NOT NULL, "assignee_address" text, "destroyer_address" text, "status" character varying(10) NOT NULL, "result" character varying(7), "impl_spec_version" integer NOT NULL, "input" text, "output" text, "proof" text, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "assigned_at" TIMESTAMP WITH TIME ZONE, "processing_at" TIMESTAMP WITH TIME ZONE, "processed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "deleted_at" TIMESTAMP WITH TIME ZONE, "_pool_id" character varying, "_policy_id" character varying, "_owner_id" character varying, "_assignee_id" character varying, "_destroyer_id" character varying, CONSTRAINT "PK_fb213f79ee45060ba925ecd576e" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_ea895dd58b2daff36df3ef9282" ON "task" ("_pool_id") `)
        await db.query(`CREATE INDEX "IDX_f64e18f353e2cbf444030bc245" ON "task" ("_policy_id") `)
        await db.query(`CREATE INDEX "IDX_a3b1cd391481292fa424c43d5d" ON "task" ("_owner_id") `)
        await db.query(`CREATE INDEX "IDX_c1baab9802e9d0a5f091e7f51b" ON "task" ("_assignee_id") `)
        await db.query(`CREATE INDEX "IDX_761968f21a7084ae219eba90f8" ON "task" ("_destroyer_id") `)
        await db.query(`CREATE INDEX "IDX_2fe7a278e6f08d2be55740a939" ON "task" ("status") `)
        await db.query(`CREATE TABLE "pool" ("id" character varying NOT NULL, "pool_id" integer NOT NULL, "owner_address" text NOT NULL, "impl_id" integer NOT NULL, "creating_task_ability" boolean NOT NULL, "metadata" text, "workers_count" integer NOT NULL, "online_workers_count" integer NOT NULL, "pending_tasks_count" integer NOT NULL, "processing_tasks_count" integer NOT NULL, "created_tasks_count" integer NOT NULL, "successful_tasks_count" integer NOT NULL, "failed_tasks_count" integer NOT NULL, "errored_tasks_count" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "deleted_at" TIMESTAMP WITH TIME ZONE, "_owner_id" character varying, "_impl_id" character varying, CONSTRAINT "PK_db1bfe411e1516c01120b85f8fe" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_b6634de97efac782ed9ea04f7b" ON "pool" ("_owner_id") `)
        await db.query(`CREATE INDEX "IDX_373ad8c35c70e61c37cfe2581c" ON "pool" ("_impl_id") `)
        await db.query(`CREATE TABLE "impl" ("id" character varying NOT NULL, "impl_id" integer NOT NULL, "owner_address" text NOT NULL, "attestation_method" character varying(6) NOT NULL, "deployment_permission" character varying(6) NOT NULL, "metadata" text, "pools_count" integer NOT NULL, "tasks_count" integer NOT NULL, "online_workers_count" integer NOT NULL, "successful_tasks_count" integer NOT NULL, "failed_tasks_count" integer NOT NULL, "errored_tasks_count" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "deleted_at" TIMESTAMP WITH TIME ZONE, "_owner_id" character varying, CONSTRAINT "PK_a8cc1327d4d3bff68326b317e75" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_36ee11c066f20ae9b2dfa87bfa" ON "impl" ("_owner_id") `)
        await db.query(`CREATE TABLE "worker_event" ("id" character varying NOT NULL, "kind" character varying(20) NOT NULL, "payload" jsonb, "block_number" integer NOT NULL, "block_time" TIMESTAMP WITH TIME ZONE NOT NULL, "_worker_id" character varying, CONSTRAINT "PK_10a145337603818a534cffc34d6" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_6579681f2dc770797e15ebc597" ON "worker_event" ("_worker_id") `)
        await db.query(`CREATE TABLE "worker" ("id" character varying NOT NULL, "owner_address" text NOT NULL, "impl_id" integer NOT NULL, "impl_build_version" integer, "status" character varying(17) NOT NULL, "impl_spec_version" integer, "attestation_method" character varying(6), "attestation_expires_at" TIMESTAMP WITH TIME ZONE, "last_attested_at" TIMESTAMP WITH TIME ZONE, "last_heartbeat_received_at" TIMESTAMP WITH TIME ZONE, "offline_at" TIMESTAMP WITH TIME ZONE, "offline_reason" character varying(24), "pools_count" integer NOT NULL, "processing_tasks_count" integer NOT NULL, "assigned_tasks_count" integer NOT NULL, "successful_tasks_count" integer NOT NULL, "failed_tasks_count" integer NOT NULL, "errored_tasks_count" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "deleted_at" TIMESTAMP WITH TIME ZONE, "_owner_id" character varying, "_impl_id" character varying, "_impl_build_id" character varying, CONSTRAINT "PK_dc8175fa0e34ce7a39e4ec73b94" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_5b866db31e6781f226ac2f0e93" ON "worker" ("_owner_id") `)
        await db.query(`CREATE INDEX "IDX_57c02a57da7d8e9c0bb9084c39" ON "worker" ("_impl_id") `)
        await db.query(`CREATE INDEX "IDX_4e903b292f3ed033f02af07ce4" ON "worker" ("_impl_build_id") `)
        await db.query(`CREATE INDEX "IDX_fdca7f90c98f110b79c5842108" ON "worker" ("status") `)
        await db.query(`CREATE TABLE "account" ("id" character varying NOT NULL, "workers_count" integer NOT NULL, "pools_count" integer NOT NULL, "created_tasks_count" integer NOT NULL, CONSTRAINT "PK_54115ee388cdb6d86bb4bf5b2ea" PRIMARY KEY ("id"))`)
        await db.query(`ALTER TABLE "impl_build" ADD CONSTRAINT "FK_fc6f6b9ac54614cd699fc5dd74a" FOREIGN KEY ("_impl_id") REFERENCES "impl"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pool_workers" ADD CONSTRAINT "FK_a1959943ab30eb084ebdee75251" FOREIGN KEY ("_pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pool_workers" ADD CONSTRAINT "FK_d5e39bcd7ed93dbc3cf61aaf705" FOREIGN KEY ("_worker_id") REFERENCES "worker"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "creating_task_policy" ADD CONSTRAINT "FK_0a1b9b9a2968014eba32b94bbbf" FOREIGN KEY ("_pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "task_event" ADD CONSTRAINT "FK_95b5d139a6cc677f8a719f3eb4e" FOREIGN KEY ("_task_id") REFERENCES "task"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "task" ADD CONSTRAINT "FK_ea895dd58b2daff36df3ef9282b" FOREIGN KEY ("_pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "task" ADD CONSTRAINT "FK_f64e18f353e2cbf444030bc2455" FOREIGN KEY ("_policy_id") REFERENCES "creating_task_policy"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "task" ADD CONSTRAINT "FK_a3b1cd391481292fa424c43d5d5" FOREIGN KEY ("_owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "task" ADD CONSTRAINT "FK_c1baab9802e9d0a5f091e7f51bd" FOREIGN KEY ("_assignee_id") REFERENCES "worker"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "task" ADD CONSTRAINT "FK_761968f21a7084ae219eba90f83" FOREIGN KEY ("_destroyer_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pool" ADD CONSTRAINT "FK_b6634de97efac782ed9ea04f7b2" FOREIGN KEY ("_owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pool" ADD CONSTRAINT "FK_373ad8c35c70e61c37cfe2581c7" FOREIGN KEY ("_impl_id") REFERENCES "impl"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "impl" ADD CONSTRAINT "FK_36ee11c066f20ae9b2dfa87bfa5" FOREIGN KEY ("_owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "worker_event" ADD CONSTRAINT "FK_6579681f2dc770797e15ebc597e" FOREIGN KEY ("_worker_id") REFERENCES "worker"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "worker" ADD CONSTRAINT "FK_5b866db31e6781f226ac2f0e93f" FOREIGN KEY ("_owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "worker" ADD CONSTRAINT "FK_57c02a57da7d8e9c0bb9084c392" FOREIGN KEY ("_impl_id") REFERENCES "impl"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "worker" ADD CONSTRAINT "FK_4e903b292f3ed033f02af07ce47" FOREIGN KEY ("_impl_build_id") REFERENCES "impl_build"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`DROP TABLE "impl_build"`)
        await db.query(`DROP INDEX "public"."IDX_fc6f6b9ac54614cd699fc5dd74"`)
        await db.query(`DROP TABLE "pool_workers"`)
        await db.query(`DROP INDEX "public"."IDX_a1959943ab30eb084ebdee7525"`)
        await db.query(`DROP INDEX "public"."IDX_d5e39bcd7ed93dbc3cf61aaf70"`)
        await db.query(`DROP TABLE "creating_task_policy"`)
        await db.query(`DROP INDEX "public"."IDX_0a1b9b9a2968014eba32b94bbb"`)
        await db.query(`DROP TABLE "task_event"`)
        await db.query(`DROP INDEX "public"."IDX_95b5d139a6cc677f8a719f3eb4"`)
        await db.query(`DROP TABLE "task"`)
        await db.query(`DROP INDEX "public"."IDX_ea895dd58b2daff36df3ef9282"`)
        await db.query(`DROP INDEX "public"."IDX_f64e18f353e2cbf444030bc245"`)
        await db.query(`DROP INDEX "public"."IDX_a3b1cd391481292fa424c43d5d"`)
        await db.query(`DROP INDEX "public"."IDX_c1baab9802e9d0a5f091e7f51b"`)
        await db.query(`DROP INDEX "public"."IDX_761968f21a7084ae219eba90f8"`)
        await db.query(`DROP INDEX "public"."IDX_2fe7a278e6f08d2be55740a939"`)
        await db.query(`DROP TABLE "pool"`)
        await db.query(`DROP INDEX "public"."IDX_b6634de97efac782ed9ea04f7b"`)
        await db.query(`DROP INDEX "public"."IDX_373ad8c35c70e61c37cfe2581c"`)
        await db.query(`DROP TABLE "impl"`)
        await db.query(`DROP INDEX "public"."IDX_36ee11c066f20ae9b2dfa87bfa"`)
        await db.query(`DROP TABLE "worker_event"`)
        await db.query(`DROP INDEX "public"."IDX_6579681f2dc770797e15ebc597"`)
        await db.query(`DROP TABLE "worker"`)
        await db.query(`DROP INDEX "public"."IDX_5b866db31e6781f226ac2f0e93"`)
        await db.query(`DROP INDEX "public"."IDX_57c02a57da7d8e9c0bb9084c39"`)
        await db.query(`DROP INDEX "public"."IDX_4e903b292f3ed033f02af07ce4"`)
        await db.query(`DROP INDEX "public"."IDX_fdca7f90c98f110b79c5842108"`)
        await db.query(`DROP TABLE "account"`)
        await db.query(`ALTER TABLE "impl_build" DROP CONSTRAINT "FK_fc6f6b9ac54614cd699fc5dd74a"`)
        await db.query(`ALTER TABLE "pool_workers" DROP CONSTRAINT "FK_a1959943ab30eb084ebdee75251"`)
        await db.query(`ALTER TABLE "pool_workers" DROP CONSTRAINT "FK_d5e39bcd7ed93dbc3cf61aaf705"`)
        await db.query(`ALTER TABLE "creating_task_policy" DROP CONSTRAINT "FK_0a1b9b9a2968014eba32b94bbbf"`)
        await db.query(`ALTER TABLE "task_event" DROP CONSTRAINT "FK_95b5d139a6cc677f8a719f3eb4e"`)
        await db.query(`ALTER TABLE "task" DROP CONSTRAINT "FK_ea895dd58b2daff36df3ef9282b"`)
        await db.query(`ALTER TABLE "task" DROP CONSTRAINT "FK_f64e18f353e2cbf444030bc2455"`)
        await db.query(`ALTER TABLE "task" DROP CONSTRAINT "FK_a3b1cd391481292fa424c43d5d5"`)
        await db.query(`ALTER TABLE "task" DROP CONSTRAINT "FK_c1baab9802e9d0a5f091e7f51bd"`)
        await db.query(`ALTER TABLE "task" DROP CONSTRAINT "FK_761968f21a7084ae219eba90f83"`)
        await db.query(`ALTER TABLE "pool" DROP CONSTRAINT "FK_b6634de97efac782ed9ea04f7b2"`)
        await db.query(`ALTER TABLE "pool" DROP CONSTRAINT "FK_373ad8c35c70e61c37cfe2581c7"`)
        await db.query(`ALTER TABLE "impl" DROP CONSTRAINT "FK_36ee11c066f20ae9b2dfa87bfa5"`)
        await db.query(`ALTER TABLE "worker_event" DROP CONSTRAINT "FK_6579681f2dc770797e15ebc597e"`)
        await db.query(`ALTER TABLE "worker" DROP CONSTRAINT "FK_5b866db31e6781f226ac2f0e93f"`)
        await db.query(`ALTER TABLE "worker" DROP CONSTRAINT "FK_57c02a57da7d8e9c0bb9084c392"`)
        await db.query(`ALTER TABLE "worker" DROP CONSTRAINT "FK_4e903b292f3ed033f02af07ce47"`)
    }
}
