version: "3"

services:
  mongo:
    image: mongo:latest
    container_name: statescan_mongo
    restart: always
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS}"
#  # Debug only
#  mongo-express:
#    image: mongo-express:latest
#    container_name: statescan_mongo_express
#    restart: always
#    ports:
#      - "8081:8081"
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
#      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_USER}:${MONGO_PASS}@statescan_mongo:${MONGO_PORT}/"
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - mongo
    container_name: statescan_backend
    restart: always
    ports:
      - "${BACKEND_SERVER_PORT}:5010"
    environment:
      MONGO_CONNECTION_STRING: "mongodb://${MONGO_USER}:${MONGO_PASS}@statescan_mongo:${MONGO_PORT}/"
      SUB_WS_RPC_ENDPOINT: "${SUB_WS_RPC_ENDPOINT}"
      SUB_CHAIN_NAME: "${SUB_CHAIN_NAME}"
      SCAN_STEP: "${SCAN_STEP}"
  website:
    build:
      context: website
      dockerfile: Dockerfile
    depends_on:
      - backend
    container_name: statescan_website
    restart: always
    ports:
      - "${WEBSITE_SERVER_PORT}:3000"
    environment:
      PUBLIC_API_END_POINT: "${BACKEND_API_HOST}/"
      SUB_CHAIN_NAME: "${SUB_CHAIN_NAME}"
